package com.servicesphere.sync

import com.servicesphere.data.local.*
import org.json.JSONObject

internal fun BusinessProfileEntity.syncPayload() = JSONObject().apply { put("businessName", businessName); put("ownerName", ownerName); put("phone", phone); put("email", email); put("address", address); put("website", website); put("taxNumber", taxNumber); put("logoUri", logoUri); put("currencyCode", currencyCode); put("taxRatePercent", taxRatePercent); put("paymentInstructions", paymentInstructions); put("quotePrefix", quotePrefix); put("invoicePrefix", invoicePrefix); put("nextQuoteNumber", nextQuoteNumber); put("nextInvoiceNumber", nextInvoiceNumber); put("createdAt", createdAt); put("updatedAt", updatedAt) }.toString()
internal fun ClientEntity.syncPayload() = JSONObject().apply { put("name", name); put("phone", phone); put("email", email); put("address", address); put("notes", notes); put("createdAt", createdAt); put("updatedAt", updatedAt) }.toString()
internal fun JobEntity.syncPayload() = JSONObject().apply { put("clientId", clientId); put("sourceQuoteId", sourceQuoteId); put("title", title); put("description", description); put("address", address); put("scheduledAt", scheduledAt); put("status", status); put("estimatedPrice", estimatedPrice); put("internalNotes", internalNotes); put("createdAt", createdAt); put("updatedAt", updatedAt) }.toString()
internal fun QuoteEntity.syncPayload() = JSONObject().apply { put("clientId", clientId); put("jobId", jobId); put("quoteNumber", quoteNumber); put("status", status); put("issueDate", issueDate); put("validUntil", validUntil); put("subtotal", subtotal); put("discountAmount", discountAmount); put("taxAmount", taxAmount); put("total", total); put("notes", notes); put("sentAt", sentAt); put("acceptedAt", acceptedAt); put("declinedAt", declinedAt); put("convertedInvoiceId", convertedInvoiceId); put("createdAt", createdAt); put("updatedAt", updatedAt) }.toString()
internal fun InvoiceEntity.syncPayload() = JSONObject().apply { put("clientId", clientId); put("jobId", jobId); put("quoteId", quoteId); put("invoiceNumber", invoiceNumber); put("status", status); put("issueDate", issueDate); put("dueDate", dueDate); put("paidDate", paidDate); put("paymentMethod", paymentMethod); put("subtotal", subtotal); put("discountAmount", discountAmount); put("taxAmount", taxAmount); put("total", total); put("notes", notes); put("sentAt", sentAt); put("voidedAt", voidedAt); put("createdAt", createdAt); put("updatedAt", updatedAt) }.toString()
internal fun LineItemEntity.syncPayload() = JSONObject().apply { put("parentId", parentId); put("parentType", parentType); put("description", description); put("quantity", quantity); put("unitPrice", unitPrice); put("total", total); put("sortOrder", sortOrder); put("createdAt", createdAt); put("updatedAt", updatedAt) }.toString()
internal fun JobPhotoEntity.syncPayload() = JSONObject().apply { put("jobId", jobId); put("localUri", localUri); put("caption", caption); put("createdAt", createdAt) }.toString()
internal fun SignatureEntity.syncPayload() = JSONObject().apply { put("jobId", jobId); put("invoiceId", invoiceId); put("localUri", localUri); put("signedBy", signedBy); put("approvalText", approvalText); put("createdAt", createdAt) }.toString()
internal fun JobReminderEntity.syncPayload() = JSONObject().apply { put("jobId", jobId); put("reminderType", reminderType); put("reminderTimeMillis", reminderTimeMillis); put("isEnabled", isEnabled); put("hasFired", hasFired); put("createdAt", createdAt); put("updatedAt", updatedAt) }.toString()
